[project]
name = "local-pdf-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.46.0",
    "langgraph>=0.2.74",
    "mcp[cli]>=1.3.0",
    "mypy>=1.15.0",
    "pypdf>=5.3.0",
    "ruff>=0.9.7",
]
